BASE_JOINT_ID = 100
SHOULDER_JOINT_ID = 101
ELBOW_JOINT_ID = 102
WRIST_JOINT_ID = 103
WRIST_TURN_JOINT_ID = 104
GRABBER_JOINT_ID = 105

INITIAL_ANGLES = {
    BASE_JOINT_ID: 000,
    SHOULDER_JOINT_ID: 000,
    ELBOW_JOINT_ID: 000,
    WRIST_JOINT_ID: 000,
    WRIST_TURN_JOINT_ID: 000,
    GRABBER_JOINT_ID: 000
}

ANGLE_BOUNDS = {
    BASE_JOINT_ID: (0, 270),
    SHOULDER_JOINT_ID: (38, 90),
    ELBOW_JOINT_ID: (10, 150),
    WRIST_JOINT_ID: (0, 180),
    WRIST_TURN_JOINT_ID: (0, 180),
    GRABBER_JOINT_ID: (80, 100)
}

SERVO_PORTS = {
    BASE_JOINT_ID: 0,
    SHOULDER_JOINT_ID: (1, 2),
    ELBOW_JOINT_ID: 3,
    WRIST_JOINT_ID: 4,
    WRIST_TURN_JOINT_ID: 5,
    GRABBER_JOINT_ID: 6
}
